# Generated by Django 5.2 on 2025-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_connectionsub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
