# Generated by Django 5.2 on 2025-04-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connectionsub_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionsub',
            name='tab',
        ),
    ]
