# Generated by Django 5.2 on 2025-04-05 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_connectionsub_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='api.connection')),
            ],
        ),
        migrations.AlterField(
            model_name='connectionsub',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtab', to='api.subtab'),
        ),
    ]
